### ISSUE TITLE
slack-ruby-bot is now deplicated by the Slack api update.

### ISSUE THREAD

**Issue by morihaya** [pyama86/slack-afk#5]
Hello. Thanks for the interesting Slack bot.
I tried it as soon as I could, but the pod `away-from-keyboard-bot` didn't start with the following error.

```
away-from-keyboard-58c99585b9-whsc2 › away-from-keyboard-bot
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot I, [2020-08-05T19:53:19.366155 #1]  INFO -- request: POST https://slack.com/api/rtm.start
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot I, [2020-08-05T19:53:19.366223 #1]  INFO -- request: Accept: "application/json; charset=utf-8"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot User-Agent: "Slack Ruby Client/0.15.1"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot Content-Type: "application/x-www-form-urlencoded"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot I, [2020-08-05T19:53:20.091924 #1]  INFO -- response: Status 200
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot I, [2020-08-05T19:53:20.092056 #1]  INFO -- response: date: "Wed, 05 Aug 2020 10:53:19 GMT"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot server: "Apache"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-slack-req-id: "b6475dcb25a66fe43658e2332944b4e4"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-oauth-scopes: "identify,channels:read,groups:read,users.profile:read,chat:write,calls:write,calls:read"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-accepted-oauth-scopes: "rtm:stream"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot access-control-expose-headers: "x-slack-req-id, retry-after"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-slack-backend: "r"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-content-type-options: "nosniff"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot expires: "Mon, 26 Jul 1997 05:00:00 GMT"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot cache-control: "private, no-cache, no-store, must-revalidate"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-xss-protection: "0"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot vary: "Accept-Encoding"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot pragma: "no-cache"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot access-control-allow-headers: "slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot strict-transport-security: "max-age=31536000; includeSubDomains; preload"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot referrer-policy: "no-referrer"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot access-control-allow-origin: "*"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot content-length: "129"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot content-type: "application/json; charset=utf-8"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot x-via: "haproxy-www-7gdi,haproxy-edge-nrt-qsuy"
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot E, [2020-08-05T19:53:20.092311 #1] ERROR -- : missing_scope (Slack::Web::Api::Errors::MissingScope)
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/response/raise_error.rb:16:in `on_complete'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/multipart.rb:25:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/request.rb:26:in `request'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/request.rb:11:in `post'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/api/endpoints/rtm.rb:42:in `rtm_start'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/real_time/client.rb:179:in `build_socket'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/real_time/client.rb:51:in `start!'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:36:in `start!'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:30:in `block (2 levels) in run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:50:in `handle_exceptions'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:28:in `block in run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:27:in `loop'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:27:in `run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot bot.rb:51:in `<main>'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot Traceback (most recent call last):
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      21: from bot.rb:51:in `<main>'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      20: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:27:in `run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      19: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:27:in `loop'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      18: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:28:in `block in run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      17: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:50:in `handle_exceptions'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      16: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:30:in `block (2 levels) in run'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      15: from /usr/local/bundle/ruby/2.6.0/gems/slack-ruby-bot-0.16.0/lib/slack-ruby-bot/server.rb:36:in `start!'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      14: from /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/real_time/client.rb:51:in `start!'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      13: from /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/real_time/client.rb:179:in `build_socket'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      12: from /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/api/endpoints/rtm.rb:42:in `rtm_start'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      11: from /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/request.rb:11:in `post'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot      10: from /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/request.rb:26:in `request'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       9: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       8: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       7: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       6: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/multipart.rb:25:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       5: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       4: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       3: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       2: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot       1: from /usr/local/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
away-from-keyboard-58c99585b9-whsc2 away-from-keyboard-bot /usr/local/bundle/ruby/2.6.0/bundler/gems/slack-ruby-client-a898c238fb38/lib/slack/web/faraday/response/raise_error.rb:16:in `on_complete': missing_scope (Slack::Web::Api::Errors::MissingScope)
```

I investigated and found the following issue in the slack-ruby-bot repository.
> AFAIK this was being deprecated and one needs to install apps via oauth workflow and all that. 
[slack-ruby/slack-ruby-bot/issues/241](https://github.com/slack-ruby/slack-ruby-bot/issues/241)

There was also [documentation for the migration](https://github.com/slack-ruby/slack-ruby-bot/blob/master/MIGRATION.md) there. 

According to [the document](https://github.com/slack-ruby/slack-ruby-bot/blob/master/DEPLOYMENT.md), it looks like we can make a classic Slack App that will work, but I haven't tried it...

**Comment by pyama86** [comment]
報告ありがとうございます！おそらく日本でしか使われないプロダクトなので日本語で大丈夫です！

頂いた内容、トークンの問題なのかなと思っておるのですが入れているトークンは、Slackアプリのトークンでしょうか？ボットのトークンでしょうか？

**Comment by pyama86** [comment]
うーむ。ちなみにいまのGemfile.lockのバージョンで新しく作ったアプリで普通に手元で動いているので、Slackの仕様の引きづられるというのがちょい解せない感じです。
![image](https://user-images.githubusercontent.com/8022082/89423237-3513fc80-d771-11ea-94fe-cab3638afa6b.png)

トークンとしては上記の画面の下に出てくるものを使っていただいてますよね？

**Comment by pyama86** [comment]
あー、てか文字通りscopeが足りないかもしれないです。

![image](https://user-images.githubusercontent.com/8022082/89423454-7ad0c500-d771-11ea-81fd-20abb5922afe.png)

```
chat:write
Send messages as @away_from_keyboard

commands
Add shortcuts and/or slash commands that people can use

incoming-webhook
Post messages to specific channels in Slack
```

このあたりのスコープ追加してもらえますか。

**Comment by morihaya** [comment]
![image](https://user-images.githubusercontent.com/18348089/89424149-5fb28500-d772-11ea-8fb9-c15231bc5405.png)

同じにしてみて、 Reinstall App もしましたがやはり同じ `missing_scope` エラーでした。

curlで直接叩いてみましたが以下のようなエラーになります。
```
 curl  "https://slack.com/api/rtm.start?token=xoxp-........."{"ok":false,"error":"missing_scope","needed":"rtm:stream","provided":"commands,channels:read,users.profile:read,chat:write:bot,calls:write,calls:read"}⏎
```

**Comment by pyama86** [comment]
ちなみにアプリ自体はワークスペースにインストールされているのですよね？

**Comment by morihaya** [comment]
はい、インストールは済んでいます。
"Install your app to your workspace"　もチェックマークがついています。
![image](https://user-images.githubusercontent.com/18348089/89426246-eb2d1580-d774-11ea-92a9-a694182f05ee.png)

**Comment by pyama86** [comment]
すみません、調べたらめっちゃ嘘ついてました。
入れるトークンは、Botsで作成したトークンでした。ほんとにすみません・・・。
![image](https://user-images.githubusercontent.com/8022082/89427832-a73b1000-d776-11ea-92bc-fac7c142bd81.png)

**Comment by morihaya** [comment]
ありがとうございます、やっぱり Real Time Messaging API (RTM) ですよね。。
となるとClassic APPを使えば良さそうでした。すっきりしたのでこちらはクローズします。（反応早すぎてびっくりしました、大変感謝です！）

https://api.slack.com/rtm

> New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.

**Comment by pyama86** [comment]
はい、もし導入されてうまくワークしたら教えてほしいです。その時はもうちょっと導入しやすいようなマニュアルなり何なり用意しようと思います。

いまペパボだと、離席時の代理応答だけじゃなくて、 `/start` で始業の通知、 `/finish` で就業の通知とかまだ拡張して使っています。その時のメッセージとかは環境変数で変えられるようにしていて、ペパボの場合は勤怠システムのURLとかをペロッと通知したりしています。

些細なことでも雑にissue立て貰えればサポートできるので困ったことがあればご連絡ください。(そしてその内容をどんどんドキュメントにしてしまう・・・)

**Comment by morihaya** [comment]
SlackのClassic App試したんですが、今からBots用のトークンははらい出せないみたいですね。
とても面白い仕組みなんですが、Slack側の仕様で今からは導入できなさそうでした。。。

**Comment by pyama86** [comment]
あれ、なんでだろう。僕とか先週末払い出したんですけど、プランの違いとか、以前から利用してるとかそういう事情があるのですかねぇ・・・。

**Comment by pyama86** [comment]
なんか別にbot.rb、大したことやっってないんで、
https://qiita.com/nekonekonekoe/items/b39cc763945bdcef35fb
このあたり参考にrewriteしちゃえば動きそうな気もしていまっす。

僕がslackのapiの変更に明るくなくて、完全に勘で書いているのですが。。

> ライブラリかえても結局rtmのスコープ持ってないから認証で落ちそうな気がする
